### PR TITLE
Correct condition to run forever checks

### PR DESCRIPTION
**Pull request by pv72895**
I was incorrectly checking `steps.run_forever.outputs.files_exists == 'true'` but it should be `steps.fail_test.outputs.diff`

Below is proof that the running forever doesn't get triggered when it shouldn't (the diff has a file called `no_not_run_forever_4.txt`

image

Below is proof that it does run when needed (you can see the step is running)

image

I also deleted all those run_forever files that should have never merged

### CODE REVIEW

**Comment by pwillett** [comment]
What is the type of `diff`? Can we write the condition such that it doesn't rely on truthiness, perhaps with a `.length > 0` or similar? An empty list is truthy in JS and falsy in Python, and I'd rather not care what's evaluating this YAML expression.

**Comment by pwillett** [comment]
> What is the type of `diff`?

Ah, you have the dump right there: array.

**Comment by pv72895** [comment]
Also, this is how the docs tell you how to do it

https://github.com/technote-space/get-diff-action#screenshots

**Comment by pwillett** [comment]
Their docs are just, like, their opinion, man.
Still, there's apparently no way to get the length of an array in GH expressions.

**Review by pwillett — APPROVED** [review]

**Pull request merged**
